### ISSUE TITLE
How can the contract be tested with a short expiration time?

### ISSUE THREAD

**Issue by Augustus-floop** [KarolTrzeszczkowski/Electron-Cash-Last-Will-Plugin#3]
I tried to change in last_will_contract.py this line:
`INHERITACNE_TIME=int((180*3600*24))`
but Electron gave an error when I tried to add the plug-in. I imagine there's some check for verification of authenticity but I have no experience with plug-ins and smart contracts.

**Comment by KarolTrzeszczkowski** [comment]
Hey! Make sure, that when you zip the plugin it has the same directory structure as the one from releases:

```
last-will-plugin.zip
|--manifest.json
|--last-will-plugin/
|--|--__init__.py
|--|--contract_finder.py
|--|--last_will_contract.py
|--|--notification_service.py
|--|--qt.py
|--|--ui.py
|--|--util.py
```
It is also worth mentioning that the time that is used here is approximate. Also usually you have to restart Electron Cash when reinstalling plugins.
Good luck!

**Comment by Augustus-floop** [comment]
Thanks Karol for replying so fast!
I changed the plugin name in manifest.json in case it's causing collusion with the original plugin:

> {
>     "display_name": "Last Will-test",
>     "version": "0.2.2",
>     "description": "Last Will-test",
>     "project_url": "https://github.com/KarolTrzeszczkowski/Electron-Cash-Plugin-Last-Will/",
>     "minimum_ec_version": "4.0",
>     "package_name": "last-will-plugin-test",
>     "available_for": [
>         "qt"
>     ]
> }

When I add it to Electron there's no error, It's just can't be enabled .

**Comment by KarolTrzeszczkowski** [comment]
Change the name back, uninstall both plugins, restart EC and then it should let you install.

**Comment by Augustus-floop** [comment]
That worked out, thanks.
Looks like the contract worked too, but I have nothing to base on and know it's "audited" and safe, it looks like a lot of code.

**Comment by KarolTrzeszczkowski** [comment]
Yes, it was not formally audited but as a first covenant contract [in existence](https://news.bitcoin.com/last-will-platform-allows-your-loved-ones-to-inherit-your-bch/), many people built their contracts based on this code or learned covenant techniques from it, so it was heavily peer reviewed. When evaluating the security you should focus on the [contract](https://github.com/KarolTrzeszczkowski/Electron-Cash-Last-Will-Plugin/blob/master/LastWill.spedn) because if it's good then all the properties hold. Also, I'm constantly working on new contracts and projects, gaining experience and expertise, and to my knowledge, the contract is a bit clumsy but still perfectly safe to use. It's important to mention that the plugin does not support hardware wallets, it will in a month or two. 

Thanks for getting interested with this project, it's very motivating for me to continue working on it :)

**Comment by Augustus-floop** [comment]
Update about my test of the contract: I tried to inherit coins from the expired contract but used 1sat/byte, so looks like it doesn't get confirmed.  Idk how to make a new tx because when I click "find existing last will contract" it says "you aren't party in any contract"... oops!

**Comment by KarolTrzeszczkowski** [comment]
The tx is probably already confirmed, but for the future, don't worry - it's not BTC, the network is not congested and people really take care it never happen, 1sat/byte 99.9% of the time go to the next block. The issue is that due to responsive difficulty adjustment algo block time variance is very high - any spikes in hashrate propagete for days. That's probably why you had to wait so long for the confirmation. 

Any way, even if you could still see this contract in the plugin, BCH has no RBF so you would not be able to bump the fee. BCH miners reject double spend attempts by default and you would have to bribe them and that's not easy. What you could do is spend the unconfirmed tx to your own address with the higher fee, it would be "child pays for parent". Tbh it would not speed anything up because 1sat/byte is already max speed :) look, there was no block found for almost 3h https://jochen-hoenicke.de/queue/#2,24h

**Comment by Augustus-floop** [comment]
It's still in the contract and I can't inherit or refresh it...
When I try to refresh it:  I click broadcast and it says 'an error occured  while broadcasting'.
When I try to inherit it:  it's 'ready to be inherited' but when I click broadcast it returns 'an error occured while broadcasting'.

**Comment by KarolTrzeszczkowski** [comment]
Could you send me txid of the funding transaction?

**Comment by Augustus-floop** [comment]
Something's going on! Now it says 'you are not party in a contract yet' and it's uncofirmed. This is the inheriting tx:
3c015d66957420c1c3047ac228461b9d9c111864fe794982fda93c68b3572c46
EDIT: and now... the tx is gone from the transactions history. It's 'ready to be inherited' once again.

**Comment by KarolTrzeszczkowski** [comment]
This is very weird. I used it many times during my tests but I have never seen anything close to this behavior. It looks like nodes first accept the transaction, add it to mempool but then remove it from the mempool? It is not supposed to happen. Could you try changing the server your Electron Cash is connected to? Click on the green button in the right bottom of EC and right-click a different node. Then try again inheriting?

**Comment by Augustus-floop** [comment]
Maybe it's because I tried to broadcast several times?

**Comment by Augustus-floop** [comment]
I asked it on Reddit, someone pointed out it's less than 1 sat/byte, so there's a rounding bug in the client? It should round it down, otherwise it won't broadcast as in this case.

**Comment by KarolTrzeszczkowski** [comment]
Okay, can you try changing the [ line #438](https://github.com/KarolTrzeszczkowski/Electron-Cash-Last-Will-Plugin/blob/master/last-will-plugin/ui.py#L438 ) 
from 
`fee = len(tx.serialize(True)) // 2 `
to 
`fee = len(tx.serialize(True)) // 2+1`

**Comment by Augustus-floop** [comment]
I changed it but now it says "you aren't party in any contract"... I'm confused.

**Comment by ghost** [comment]
Would it be possible to adjust the time period of the contract in the interface of the plugin in EC itself? It would open up many more use cases if you are able to easily adjust it to a short time period of a very long time period.

**Comment by KarolTrzeszczkowski** [comment]
@94b42c29dd could you please open a new issue for this feature request? It is absolutely possible and it was on my roadmap but I got distracted by other projects.

**Comment by KarolTrzeszczkowski** [comment]
@Augustus-floop did it work finally? If you want me to help you I need more informations. The best would be txid of the funding transaction or a saved redeem (inherit) transaction file.

**Comment by Augustus-floop** [comment]
Looks like it was finally acceppted in a block ...
I can see the balance now. So it was the edge case when the fee was just below 1sat? Are you going to commit the change to the code?

**Comment by Augustus-floop** [comment]
And now I just can't end the contract and deposit it to the cold storage address. I tried to add the address to a watch only wallet but no end contract option shows.

**Comment by KarolTrzeszczkowski** [comment]
Could you please start a new issue, describe your problem, post a screenshot and give me the funding transaction id so I can do anything at all to identify the problem? Simply saying "it doesn't work" is not enough for me to help you. Please describe the problem in details. If you are concerned about privacy, reach me on telegram on email.

**Comment by Augustus-floop** [comment]
I'll start a new issue when I get to it... I'll donate $5 now since you've been helpful.

**Comment by KarolTrzeszczkowski** [comment]
Thank you! :)
